# Generated by Django 5.0.6 on 2024-05-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('map', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('eliminations', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('healing', models.IntegerField()),
                ('mitigation', models.IntegerField()),
            ],
        ),
    ]
