# Generated by Django 5.0.6 on 2024-06-17 05:30

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_gamelog_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValGameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valDate', models.DateTimeField()),
                ('valMap', models.CharField(max_length=100)),
                ('valResult', models.CharField(max_length=50)),
                ('agent', models.CharField(max_length=50)),
                ('valStart', models.CharField(max_length=50)),
                ('kills', models.IntegerField()),
                ('assist', models.IntegerField()),
                ('death', models.IntegerField()),
                ('econRating', models.IntegerField()),
                ('plants', models.IntegerField()),
                ('defuses', models.IntegerField()),
                ('combatScore', models.IntegerField()),
                ('user', models.ForeignKey(default=app.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
